  version: '3.8'
  services:
    backend:
      build: ./backend
      container_name: vibematch-backend
      ports:
        - "4000:4000"
      env_file:
        - ./backend/.env
      restart: unless-stopped

    frontend:
      build: ./frontend
      container_name: vibematch-frontend
      ports:
        - "8080:80"
      environment:
        - VITE_API_URL=http://localhost:4000/v1
      depends_on:
        - backend
      restart: unless-stopped

